-- ============================================
-- Job Pipeline Schema for Supabase
-- ============================================

-- Custom ENUM types
CREATE TYPE job_field AS ENUM ('AI_ENGINEER', 'TEACHING', 'PHD', 'MARKETING');
CREATE TYPE application_status AS ENUM ('NEW', 'CV_TWEAKED', 'APPLIED', 'REJECTED');

-- Table: sponsored_companies
-- Stores companies known to offer visa sponsorship
CREATE TABLE IF NOT EXISTS sponsored_companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL UNIQUE,
    industry TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add index for fast company name lookups
CREATE INDEX IF NOT EXISTS idx_sponsored_companies_name
    ON sponsored_companies(company_name);

-- Table: jobs
-- Stores discovered job openings with sponsorship
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    job_title TEXT NOT NULL,
    job_url TEXT NOT NULL UNIQUE, -- Prevents duplicates
    description TEXT NOT NULL,
    field job_field NOT NULL,
    status application_status NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_field ON jobs(field);
CREATE INDEX IF NOT EXISTS idx_jobs_company ON jobs(company_name);
CREATE INDEX IF NOT EXISTS idx_jobs_created ON jobs(created_at DESC);

-- Table: master_cvs
-- Stores one master CV template per job field/niche
CREATE TABLE IF NOT EXISTS master_cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field job_field NOT NULL UNIQUE, -- One master CV per niche
    cv_content_markdown TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: tweaked_cvs
-- Stores AI-tailored CVs for specific jobs
CREATE TABLE IF NOT EXISTS tweaked_cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE UNIQUE,
    tailored_cv_markdown TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add index for job lookups
CREATE INDEX IF NOT EXISTS idx_tweaked_cvs_job_id ON tweaked_cvs(job_id);

-- ============================================
-- Helper Functions
-- ============================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for jobs table
DROP TRIGGER IF EXISTS update_jobs_updated_at ON jobs;
CREATE TRIGGER update_jobs_updated_at
    BEFORE UPDATE ON jobs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger for master_cvs table
DROP TRIGGER IF EXISTS update_master_cvs_updated_at ON master_cvs;
CREATE TRIGGER update_master_cvs_updated_at
    BEFORE UPDATE ON master_cvs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Sample Data (Optional)
-- ============================================

-- Insert some known UK companies that sponsor visas
INSERT INTO sponsored_companies (company_name, industry) VALUES
    ('DeepMind', 'AI/ML'),
    ('Revolut', 'FinTech'),
    ('Monzo', 'FinTech'),
    ('Improbable', 'Gaming/Tech'),
    ('Babylon Health', 'HealthTech'),
    ('Darktrace', 'Cybersecurity'),
    ('BenevolentAI', 'AI/ML'),
    ('Oxford University', 'Education'),
    ('Cambridge University', 'Education'),
    ('Imperial College London', 'Education')
ON CONFLICT (company_name) DO NOTHING;

-- ============================================
-- Views for Dashboard
-- ============================================

-- View: Recent jobs needing CV tailoring
CREATE OR REPLACE VIEW jobs_pending_cv AS
SELECT
    j.id,
    j.company_name,
    j.job_title,
    j.job_url,
    j.field,
    j.status,
    j.created_at
FROM jobs j
WHERE j.status = 'NEW'
ORDER BY j.created_at DESC;

-- View: Jobs by field with stats
CREATE OR REPLACE VIEW jobs_stats_by_field AS
SELECT
    field,
    COUNT(*) as total_jobs,
    COUNT(*) FILTER (WHERE status = 'NEW') as new_jobs,
    COUNT(*) FILTER (WHERE status = 'CV_TWEAKED') as cv_tweaked,
    COUNT(*) FILTER (WHERE status = 'APPLIED') as applied,
    COUNT(*) FILTER (WHERE status = 'REJECTED') as rejected
FROM jobs
GROUP BY field;

-- ============================================
-- RLS Policies (Optional - Enable if needed)
-- ============================================

-- If you want Row Level Security:
-- ALTER TABLE sponsored_companies ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE master_cvs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE tweaked_cvs ENABLE ROW LEVEL SECURITY;

-- Example policy (adjust based on your auth setup):
-- CREATE POLICY "Allow authenticated users to read all"
--     ON jobs FOR SELECT
--     TO authenticated
--     USING (true);
